version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "awslambda-devops-pipelining-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tbp2wixwosgx"
s3_prefix = "awslambda-devops-pipelining-test"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=145870414727.dkr.ecr.us-west-1.amazonaws.com/awslambda-devops-pipelining-test"]
